// routes/ai.js
import express from 'express';
import dotenv from 'dotenv';
import fetch from 'node-fetch';

dotenv.config();

const router = express.Router();

router.post('/analyze-resume', async (req, res) => {
  const { resumeText } = req.body;

  try {
    const prompt = `Analyze the following resume and provide constructive feedback, skill gaps, and improvement tips:\n\n${resumeText}`;

    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          { role: 'system', content: 'You are a career coach and resume expert.' },
          { role: 'user', content: prompt }
        ]
      })
    });

    const data = await response.json();
    const feedback = data.choices?.[0]?.message?.content || 'No feedback generated.';

    res.json({ feedback });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to analyze resume' });
  }
});

router.post('/generate-roadmap', async (req, res) => {
  const { targetRole, experienceLevel, careerGoal } = req.body;

  const prompt = `Create a personalized 5-step career roadmap for someone targeting the role of "${targetRole}" with experience level "${experienceLevel}" and a goal to "${careerGoal}".`;

  // Debug: Print the API key being used
  console.log('Using OpenRouter API key:', process.env.OPENROUTER_API_KEY);

  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          { role: 'system', content: 'You are an expert career advisor.' },
          { role: 'user', content: prompt }
        ]
      })
    });

    const data = await response.json();
    console.log('OpenRouter response:', data);

    if (!data.choices || !data.choices[0] || !data.choices[0].message) {
      return res.status(500).json({ error: data.error?.message || 'No roadmap generated by AI.' });
    }

    const roadmap = data.choices[0].message.content.split('\n').filter(line => line.trim());
    res.json({ roadmap });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate roadmap' });
  }
});

export default router;
